### ISSUE TITLE
Scratch game

### ISSUE THREAD

**Issue by aneelabaji** [ahmemon/asteroidAttackScratch#10]
Steps:
1.Click on this link https://scratch.mit.edu/projects/203035114/#editor

actual:
instead of game this website appears

![image](https://user-images.githubusercontent.com/36023424/36058616-29094cd2-0dda-11e8-98c3-79808b1f734d.png)

Expected:
The game should have started for playing

**Comment by aneelabaji** [comment]
version 5.4

**Comment by IbrahimAMemon** [comment]
Scratch's bug
