### ISSUE TITLE
Spaceship speed

### ISSUE THREAD

**Issue by aneelabaji** [ahmemon/asteroidAttackScratch#7]
Steps:
1.Press the f button to move fast using the turbo booster

Actual:
The spaceship did not move fast, in fact the screen did

Expected:
The space ship will go fast by using its turbo booster inshaAllah

**Comment by aneelabaji** [comment]
version 5.2

**Comment by IbrahimAMemon** [comment]
you already filed this and it is wrong. The ship never moves forward, only the asteroids move faster. This produces the effect of the ship moving faster.
