### ISSUE TITLE
1up mushroom

### ISSUE THREAD

**Issue by aneelabaji** [ahmemon/asteroidAttackScratch#9]
Steps:
2.wait at least 45 seconds

Actual:
The mushroom comes in 60 seconds in a straight line

Expected:
The mushroom animation will be coming in a straight line inshaAllah

**Comment by aneelabaji** [comment]
version 5.2

**Comment by ahmemon** [comment]
If the mushroom is already coming in a straight line, then it's not a bug right? I don't understand what the problem is here.
